#!/usr/bin/perl

# TODO:
# make this a class, so you can easily have multiple with different parameters
# eg values of N, threshold, different inputs (ip, networks, url segment, user agent)

use strict;
my $N = shift @ARGV;    # how big our window is
my $threshold = shift @ARGV;    # threshold for reporting

my @ring;  # ring buffer, accessed [i mod N]
my %seen;  # hash of what's seen
my $actual_max = 0;

my $i = 0;  # index counter  (same as $.)
while (<>) {
  next if m/:80 ::1 /;
  chomp;
  if (! m/^[a-z.]+:80 ([0-9.]+) / ) {
    warn "nomatch: $_";
    next;
  }
  my $this_ip = $1;

  # pop from ring
  my $popped = $ring[ $i % $N ];
  if ( $popped != '' ) {
    if ( $popped == $this_ip ) {
      # no counts to adjust
      # still warn about threshold ?
    } else {
      if ( $seen{$popped}-- == $threshold ) {
	printf("%5d: .. below: %s\n", $i,  $this_ip);
      }
    }     
  }
  
  # push in ring / add count seen (>threshold?  watchlist?)
  if ( $popped == $this_ip ) {
    # handled above
  } else {
    $ring[ $i % $N ] = $this_ip;
    $seen{$this_ip}++;
    if ( $seen{$this_ip} == 2 * $threshold ) {
      printf("%5d: .. ABOVE ABOVE: %s\n", $i,  $this_ip);
    } elsif ( $seen{$this_ip} == $threshold ) {
      printf("%5d: .. above: %s\n", $i,  $this_ip);
    }
    if ( $seen{$this_ip} > $actual_max ) {
      $actual_max = $seen{$this_ip};
    }
  }

  $i++;
  # every N we could output some stats such as:
  # highest peak
  # current highest entry
  if ( $i % $N == 0 ) {
    dump_some_status($_);    
  }
}

# TODO  handle rotating logs

sub dump_some_status {
  my $line = $_[0];
  my $datetime = ''; # just for humans
  # newchristianbiblestudy.org:80 207.46.13.133 - - [24/Apr/2016:06:53:32 +0000] "GET
  # (\d\d/.../\d\d\d\d:\d\d:\d\d:\d\d
  if ( $line =~ m=\[([^\]]+)\]= ) {
    $datetime = $1;
  } else {
    warn "can't parse time! - $_";
    $datetime = `date`;
    chomp($datetime);
  }
  # $. not same  as $i, because of number of ignored
  print "============================================ Reached $. lines!   -  $datetime\n";
  sub by_value {
    #$main::seen->{$b} <=> $main::seen->{$a};
    $seen{$b} <=> $seen{$a};
  }

  my @names = sort by_value keys %seen;
  printf "# peak 1:  %4d   %s\n", $seen{ $names[0] }, $names[0] ;
  printf "# peak 2:  %4d   %s\n", $seen{ $names[1] }, $names[1] ;
  printf "#          %4d  - actual max this period, threshold is %d\n", $actual_max, $threshold;
  $actual_max = 0;
}
      
