#!/bin/sh
version='$Id: ursy 1851 2014-09-25 18:51:07Z todd $'

# usual rsync -- parameters & output,
#  also log it

# arguments:  src(s) and dests
#   (like rsync)

scriptlog="$HOME/.logs/ursy"

[ -d "$HOME/.logs" ] || mkdir "$HOME/.logs"

# rsync  -av --progress --stats $@
# -s
# --partial
#
#        -a, --archive               archive mode; equals -rlptgoD (no -H,-A,-X)
#             --no-OPTION             turn off an implied OPTION (e.g. --no-D)
#        -r, --recursive             recurse into directories
#        -l, --links                 copy symlinks as symlinks
#        -p, --perms                 preserve permissions
#        -t, --times                 preserve modification times
#        -g, --group                 preserve group
#        -o, --owner                 preserve owner (super-user only)
#        -D                          same as --devices --specials

# to ignore group (if chgrp warnings),  --no-g
# similarly:  --no-o

cmd='rsync  -av --progress --stats --protect-args --timeout=30'  # just add $@

timestamp=`date +%Y%m%d.%H%M%S`
(echo "# $timestamp :: $version"; \
 echo "# wd: " `/bin/pwd`; \
 echo "# $0 arguments: $@"; \
 echo "$cmd $@")            >> $scriptlog

#
if $cmd "$@"; then
  status=$?
  statusmsg="success ($status)"
else 
  status=$?
  statusmsg="FAIL ($status)"
fi

timestamp=`date +%Y%m%d.%H%M%S`
(echo "# $timestamp completed:  $statusmsg"; \
 echo )  >> $scriptlog

exit $status




# rsync
# --delete --backup --backup-dir=/Users/todd/Bitcasa/Bitcasa.ROOT/Bitcasa-dump/original-tk/todd.BAK
# --suffix=.20140505.0740 --bwlimit=540
# -s --timeout=210
# -av --partial --progress --stats
# /Users/todd/DONT_BACKUP /Users/todd/Bitcasa/Bitcasa.ROOT/Bitcasa-dump/original-tk/todd


